---
- name: Tools Setup
  hosts: jenkins-servers
  become: true
  gather_facts: true
  tasks:
    - name: Tools Installation
      apt:
        name: "{{ tools }}"
        state: latest
      when: ansible_distribution == "Ubuntu"
