#cloud-config
package_update: true
package_upgrade: true
hostname: pulumimachine

# create the docker group
groups:
  - docker

apt:
  sources:
    docker:
      source: deb [arch="amd64"] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      keyserver: 'https://download.docker.com/linux/ubuntu/gpg'

packages:
  - net-tools
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

write_files:
  - path: /home/ubuntu/site-content/index.html
    permissions: '0666'
    content: |
      This is my website:
  - path: /home/ubuntu/content.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      public_ip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
      private_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
      echo "Public IP Address: $public_ip" >> /home/ubuntu/site-content/index.html
      echo "Private IP Address: $private_ip" >> /home/ubuntu/site-content/index.html

runcmd:
  - /home/ubuntu/content.sh
  - usermod -G docker -a ubuntu
  - docker pull nginx:latest
  - docker run -it --rm -d -p 80:80 --name web -v /home/ubuntu/site-content:/usr/share/nginx/html nginx

final_message: |
  cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime